"""add about_me

Revision ID: 656779e2869c
Revises: 25d9b24b3519
Create Date: 2021-12-17 00:39:50.283221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656779e2869c'
down_revision = '25d9b24b3519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
